# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  LLVM_VER: 20

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Clang ${{ env.LLVM_VER }} and libc++
      run: |
        # Download the official LLVM repo setup script
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        # Install Clang, then manually install the matching libc++ headers
        sudo ./llvm.sh ${{ env.LLVM_VER }}
        sudo apt-get install -y libc++-${{ env.LLVM_VER }}-dev libc++abi-${{ env.LLVM_VER }}-dev

    - name: Get submodules
      run : git submodule update --init --recursive
      
    - name: Configure CMake
      env:
        CC: clang-${{ env.LLVM_VER }}
        CXX: clang++-${{ env.LLVM_VER }}
        CXXFLAGS: -stdlib=libc++
        LDFLAGS: -stdlib=libc++
      run: >
        cmake -B ${{github.workspace}}/build 
        -DCMAKE_C_COMPILER=clang-${{ env.LLVM_VER }}
        -DCMAKE_CXX_COMPILER=clang++-${{ env.LLVM_VER }}
        -DCMAKE_CXX_FLAGS="-stdlib=libc++"
        -DCMAKE_EXE_LINKER_FLAGS="-stdlib=libc++"
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j $(nproc)

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}

